# Etapa 1: Construção
FROM node:20-alpine AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Gera os arquivos otimizados para produção
RUN npm run build

# Etapa 2: Servindo os arquivos com Nginx
FROM nginx:alpine

# Copia os arquivos da build para a pasta do Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expor a porta 80
EXPOSE 80

# Rodar o Nginx
CMD ["nginx", "-g", "daemon off;"]
