# Usa a imagem oficial do Node.js
FROM node:20-alpine

# Define a pasta de trabalho
WORKDIR /app

# Copia apenas os arquivos essenciais
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Variável para forçar detecção de mudanças nos arquivos
ENV CHOKIDAR_USEPOLLING=true

# Expõe a porta do Vite
EXPOSE 5173

# Comando para rodar o Vite no modo dev
CMD ["npm", "run", "dev", "--", "--host"]

