# Use imagem oficial do Python
FROM python:3.10

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos
COPY . /app

# Instala as dependências
RUN pip install --upgrade pip \
 && pip install -r requirements.txt

# Expõe a porta que o Django usará
EXPOSE 8000

# Comando padrão
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
